// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTWySEPqTKXfVjWGFnNHe9OgXQm2svUhE',
    appId: '1:124317861334:android:6f55428fd160046cbe9077',
    messagingSenderId: '124317861334',
    projectId: 'live13-15437',
    storageBucket: 'live13-15437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUDL6xJwdo6CvO9Qf8AcxnDf2KjlHtMMk',
    appId: '1:124317861334:ios:d9ae7efcd192962cbe9077',
    messagingSenderId: '124317861334',
    projectId: 'live13-15437',
    storageBucket: 'live13-15437.appspot.com',
    androidClientId: '124317861334-3rscslfe1a8cbi7rnfg91g20nk7lvd6a.apps.googleusercontent.com',
    iosClientId: '124317861334-eefdkscmeudv28vv24icis57v8c4eq6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.live13',
  );

}